on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Needed because of https://github.com/actions/checkout/issues/290
      - name: Fetch annotated tags
        run: git fetch --force --tags

      - name: Read annotated tag body
        run: |
          ./debug
          echo "RELEASE_NOTES=$(./rel_notes)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ env.RELEASE_NOTES }}
