on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read annotated tag body
        run: |
          latest_tag=$(git describe --abbrev=0)
          body=$(git tag --list --format='%(body)' $latest_tag)
          echo "RELEASE_NOTES=$(echo $body | sed '/^-----BEGIN PGP/,/^-----END PGP/d')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ env.RELEASE_NOTES }}
